### ISSUE TITLE
Godot 4?

### ISSUE THREAD

**Issue by elvisish** [io12/godot-portal-demo#1]
Love how your portals example is shaping up, do you expect GD4 to add custom projection matrices and stencil buffering?

**Comment by io12** [comment]
I haven't worked on this for the past year (in part because of the lack of those features). Looking into it again, it seems like Godot moved to a new issue tracker, and custom projection matrices were opened as an issue a few days ago (https://github.com/godotengine/godot-proposals/issues/2713), and I couldn't find an issue for stencil buffering. So, probably unlikely that GD4 will have them?

**Comment by elvisish** [comment]
Is stencil buffering necessary for portals? I understood that it's were useful as another method for making portals, but I thought having access to the camera matrix was enough?

**Comment by io12** [comment]
It's not a hard requirement, but helps a lot for performance. The current method renders the entire screen resolution to a texture for each portal, then cuts out the part that's actually visible in the portal (which is usually a small fraction of the whole screen). This is really wasteful, because if you have two portals and are playing the game on a 1080p monitor, then it's as slow as as playing with 3 1080p monitors.
